### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SuperKali** [Muqsit/NetworkQuery#4]
Warning: file_get_contents(): Failed to enable crypto in /root/NetworkGamesPE/plugins/Netw
orkQuery-master/src/NetworkQuery/tasks/AsyncQueryTask.php on line 44                      
                                                                                          
Warning: file_get_contents(https://use.gameapis.net/mcpe/query/extensive/play.networkgames
.eu): failed to open stream: operation failed in /root/NetworkGamesPE/plugins/Networ
kQuery-master/src/NetworkQuery/tasks/AsyncQueryTask.php on line 44                        
                                                                                          
Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:   
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /r
oot/NetworkGamesPE/plugins/NetworkQuery-master/src/NetworkQuery/tasks/AsyncQueryTask.php o
n line 44                                                                                 
                                                                                          
Warning: file_get_contents(): Failed to enable crypto in /root/NetworkGamesPE/plugins/Netw
orkQuery-master/src/NetworkQuery/tasks/AsyncQueryTask.php on line 44                      
                                                                                          
Warning: file_get_contents(https://use.gameapis.net/mcpe/query/extensive/play.networkgames
.eu): failed to open stream: operation failed in /root/NetworkGamesPE/plugins/Networ
kQuery-master/src/NetworkQuery/tasks/AsyncQueryTask.php on line 44                        
                                                                                          
Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:   
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /r
oot/NetworkGamesPE/plugins/NetworkQuery-master/src/NetworkQuery/tasks/AsyncQueryTask.php o
n line 44                                                                                 
                                                                                          
Warning: file_get_contents(): Failed to enable crypto in /root/NetworkGamesPE/plugins/Netw
orkQuery-master/src/NetworkQuery/tasks/AsyncQueryTask.php on line 44                      
                                                                                          
Warning: file_get_contents(https://use.gameapis.net/mcpe/query/extensive/vanilla.networ
kgames.eu): failed to open stream: operation failed in /root/NetworkGamesPE/plugins/
NetworkQuery-master/src/NetworkQuery/tasks/AsyncQueryTask.php on line 44                  
                                                                                          
Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:   
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /r
oot/NetworkGamesPE/plugins/NetworkQuery-master/src/NetworkQuery/tasks/AsyncQueryTask.php o
n line 44                                                                                 
                                                                                          
Warning: file_get_contents(): Failed to enable crypto in /root/NetworkGamesPE/plugins/Netw
orkQuery-master/src/NetworkQuery/tasks/AsyncQueryTask.php on line 44                      
                                                                                          
Warning: file_get_contents(https://use.gameapis.net/mcpe/query/extensive/up.server.cok): failed to open stream: operation failed in /root/NetworkGamesPE/plugins/Netwo
rkQuery-master/src/NetworkQuery/tasks/AsyncQueryTask.php on line 44                       
                                                                                          
Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:   
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /r
oot/NetworkGamesPE/plugins/Net

**Comment by Muqsit** [comment]
looks like an issue with OpenSSL, which version of OpenSSL are you using?

**Comment by SuperKali** [comment]
I don't know

**Comment by NycuRO** [comment]
Same problem @Muqsit .

**Comment by ghost** [comment]
I get the same error

**Comment by ghost** [comment]
@VoliPlays Daca esti prost si nu stii sa rezolvi =)))

**Comment by Muqsit** [comment]
```
Warning: file_get_contents(https://use.gameapis.net/mcpe/query/extensive/vanilla.networ
kgames.eu): failed to open stream: operation failed in /root/NetworkGamesPE/plugins/
NetworkQuery-master/src/NetworkQuery/tasks/AsyncQueryTask.php on line 44
```
You've modified the plugin and changed Network::MC_API link, sorry I can't fix that.

**Comment by ghost** [comment]
@Muqsit Bug. MaxPlayers not work correctly, it's anyway 1. 

And bug on PlayersOnline ,if enter 1 , get +100.

**Comment by SuperKali** [comment]
@Muqsit I changed it because it did not even go with mcapi.ca

**Comment by SuperKali** [comment]
It does not even work with mcapi.ca from the same problem

**Comment by SuperKali** [comment]
this is a valid problem @Muqsit

**Comment by FunnyBuddys** [comment]
Same Problem
`01:28:55] [Asynchronous Worker #1 thread/CRITICAL]: ErrorException: "file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed" (EXCEPTION) in "plugins/NetworkQuery-master/src/NetworkQuery/tasks/AsyncQueryTask" at line 44
[01:28:55] [Asynchronous Worker #1 thread/DEBUG]: #0 (): pocketmine\error_handler(integer 2, string file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:.error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed, string /home/joinserver/plugins/NetworkQuery-master/src/NetworkQuery/tasks/AsyncQueryTask.php, integer 44, array Array())
[01:28:55] [Asynchronous Worker #1 thread/DEBUG]: #1 plugins/NetworkQuery-master/src/NetworkQuery/tasks/AsyncQueryTask(44): file_get_contents(string http://mcapi.ca/query/spirit.cosmicpe.me:19132/mcpe)
[01:28:55] [Asynchronous Worker #1 thread/DEBUG]: #2 src/pocketmine/scheduler/AsyncTask(67): NetworkQuery\tasks\AsyncQueryTask->onRun()
[01:28:55] [Asynchronous Worker #1 thread/DEBUG]: #3 (): pocketmine\scheduler\AsyncTask->run()
[01:28:55] [Server thread/CRITICAL]: Could not execute asynchronous task AsyncQueryTask: Task crashed`
